Minor fixes

diff --git a/tele b/tele
--- a/tele
+++ b/tele
@@ -1,7 +1,7 @@
 #!/bin/bash
 # tele © GPLv3 by Mike Lalumiere 2018
 # This file is licensed under the GPLv3. Please see LICENSE.
-# Requires ffmpeg, avplay, and ssh. Assumes PulseAudio for mic input.
+# Requires ffmpeg, ffplay, and ssh. Assumes PulseAudio for mic input.
 tele() {
     # usage string
     read -r -d '' use <<EOF
@@ -65,12 +65,12 @@ EOF
         return 2
     fi
     # require libav tools here and on the target host
-    if ! type ffmpeg avplay &>/dev/null; then
-        printf "Missing tools on local host - ffmpeg and avplay required!\n" >&2
+    if ! type ffmpeg ffplay &>/dev/null; then
+        printf "Missing tools on local host - ffmpeg and ffplay required!\n" >&2
         return 3
     fi
-    if ! ssh "$host" -- 'bash -c "type ffmpeg avplay"' &>/dev/null; then
-        printf "Missing tools on remote host - ffmpeg and avplay required!\n" >&2
+    if ! ssh "$host" -- 'bash -c "type ffmpeg ffplay"' &>/dev/null; then
+        printf "Missing tools on remote host - ffmpeg and ffplay required!\n" >&2
         return 3
     fi
     # when signaled kill the whole process group
@@ -85,7 +85,7 @@ EOF
             fi
         } | {
             DISPLAY=:0 ssh "$host" -- \
-                   avplay -nodisp -v quiet -f wav - \
+                   ffplay -nodisp -v quiet -f wav - \
                    1>/dev/null
         } &
         printf "Sending audio stream to %s\n" "$host" >&2
@@ -99,7 +99,7 @@ EOF
             if [ -n "$out" ]; then
                 DISPLAY=:0 ffmpeg -v quiet -f wav -i - "$out"
             else
-                DISPLAY=:0 avplay -nodisp -v quiet -f wav - 1>/dev/null
+                DISPLAY=:0 ffplay -nodisp -v quiet -f wav - 1>/dev/null
             fi
         } &
         printf "Receiving audio stream from %s\n" "$host" >&2
