In transcode: remove pointless trap, make shellcheck happy.

diff --git a/transcode b/transcode
--- a/transcode
+++ b/transcode
@@ -5,26 +5,24 @@
 
 function transcode {
     # usage string
-    local usage="USAGE: $(basename $0) FORMAT SOURCE_DIR TARGET_DIR\n"
+    local usage="USAGE: transcode FORMAT SOURCE_DIR TARGET_DIR"
     # requirements
     if ! type avconv &>/dev/null; then printf "No avconv available!\n" >&2; exit 1; fi
     if ! type find   &>/dev/null; then printf "No find available?\n" >&2; exit 1; fi
     # audio format argument
     local fmt="$1"
-    if [ -z "$fmt" ]; then printf "${usage}Format argument is required!\n" >&2; exit 1; fi
+    if [ -z "$fmt" ]; then printf "%s\nFormat argument is required!\n" "$usage" >&2; exit 1; fi
     # TODO - validate format argument using 'avconv -formats'
     # source directory argument
     local src="$2"
-    if ! [ -n "$src" ]; then printf "${usage}Source directory argument is required!\n" >&2; exit 1; fi
-    if ! [ -d "$src" ]; then printf "${usage}Source $src is not a directory!\n" >&2; exit 1; fi
+    if ! [ -n "$src" ]; then printf "%s\nSource directory argument is required!\n" "$usage" >&2; exit 1; fi
+    if ! [ -d "$src" ]; then printf "%s\nSource $src is not a directory!\n" "$usage" >&2; exit 1; fi
     src="${src%%/}"
     # destination directory argument
     local dst="$3"
-    if ! [ -n "$dst" ]; then printf "${usage}Target directory argument is required!\n" >&2; exit 1; fi
-    if ! [ -d "$dst" ]; then printf "${usage}Target $dst is not a directory!\n" >&2; exit 1; fi
+    if ! [ -n "$dst" ]; then printf "%s\nTarget directory argument is required!\n" "$usage" >&2; exit 1; fi
+    if ! [ -d "$dst" ]; then printf "%s\nTarget $dst is not a directory!\n" "$usage"  >&2; exit 1; fi
     dst="${dst%%/}"
-    # setup trap so loop can be killed cleanly
-    trap "exit" SIGTERM SIGINT
     # search for track files
     # TODO - generate this regex from 'avconv -formats'
     readarray -t tracks < <(find "$src" -type f -iregex ".*\(flac\|mp3\|mp4\|ogg\|wav\)$")
@@ -40,7 +38,7 @@ function transcode {
         seg="${inp##$src/}"
         out="$dst/${seg%%\.$ext}.$fmt"
         # write out progress
-        printf "Track %d / %d - %s " "$(($num+1))" "${#tracks[@]}" "${inp##$src/}" >&2
+        printf "Track %d / %d - %s " "$(( num + 1 ))" "${#tracks[@]}" "${inp##$src/}" >&2
         # maybe setup output directory
         if ! [ -d "${out%/*}" ] && ! mkdir -p "${out%/*}"; then
             printf "Could not make directory.\n" >&2;
